### ISSUE TITLE
[Improvement] Improve FireflyDB#compaction to read fileTable from map.kryo at start time

### ISSUE THREAD

**Issue by suyashpatel98** [godcrampy/fireflydb#25]
I have the following questions:
1. Why is the fileTable object always being instantiated from scratch at start time. Why not read the existing map.kryo file to populate the fileTable at start time? I understand that you might be concerned about the scenario where the same key's value is being updated but we are setting the filePointer in the fileTable every time a key's value is updated
2. Why orphanize all log files at start time and copy over segments to a new log file? The file table has information about the latest value of each key.

There is a SerializedPersistableFileTable#fromFile method that is not being used anywhere in the firefly code base. Why not use it to do the above?

Maybe you have thought about this and I am missing something but I cannot think about what is it that I am missing.

**Comment by godcrampy** [comment]
Hi Suyash, Thanks for your questions.

1. When we restart the software, we're not sure about how it exited the last time. There could be a case where the hardware crashed, and the `map.kryo` is not the final memory representation. Or maybe the `map.kryo` file is corrupted.
2. The startup is also when we have a few milliseconds to spare, which becomes expensive when the system operates under load. Hence, I chose to orphanize all the files. The fundamental idea of compaction here is that a file may have a limit on the maximum size it can hold based on the underlying file-system spec.

The `SerializedPersistableFileTable#fromFile` is from when I hadn't implemented compaction. If I don't find a reason to keep it, I'll get rid of it.
